name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run build:doc:gitPage
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: publish NPM
        run: pnpm run action:pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: publish doc to NPM
        run: |
          pnpm run build:doc:unpkg  
          pnpm run action:doc:pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
